### ISSUE TITLE
Trouble installing lifemapper on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by cuau-cabrera** [lifemapper/LmQGIS#1]
Hi group,

I'm working on Qgis wien 2.8 and I've just upgraded my Ubuntu version to 16.04 LTS. When I try to install lifemapper I get this error message "Complement is broken: cannot import name NavigationToolbar2QTAgg" Does anybody know what is this error message about and how can I fix it?
Thanks for your help!

**Comment by jcavner** [comment]
Pushed a bug fix to the QGIS repository.  Uninstall current plugin.
Revisit QGIS repository and install again.  Fixed version of the plugin is
the same, installer will grab the correct one.

**Comment by cuau-cabrera** [comment]
Thank you so much! 

I've just installed the plugin and there was no trouble with the installation and it's working again.
